### ISSUE TITLE
Add new feature to redirect for base URL

### ISSUE THREAD

**Issue by manmath** [neos/redirecthandler#12]
As a developer, I want to add new feature to be possible to redirect for base URL. For example:
`./flow redirect:add --source=/ --target=under-construction.html --status-code=302`
So when we access `http://www.example.com` it should redirect to `http://www.example.com/under-construction.html`
Reason to have this feature to prevent any incident errors during deploy the new release to production.

**Comment by Sebobo** [comment]
This might be possible now if you change the order of the routing:

```
Neos:
  Flow:
    http:
      chain:
        process:
          chain:
            redirect:
              position: 'before routing'
              component: Neos\RedirectHandler\RedirectComponent
```
